name: money
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_gen: ^4.3.0
  icon_font_generator: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/icons/AppIcons.ttf


flutter_intl:
  enabled: true

